### ISSUE TITLE
App crashing after rotating in MainActivity

### ISSUE THREAD

**Issue by nnam-ibe** [janacm/Momenta-Capstone#116]
Rotating to landscape in MainActivity causes the app to crash.

Steps to reproduce
* In any of the fragments of the MainActivity, rotate to landscape.
![screen shot 2017-05-26 at 22 12 27](https://cloud.githubusercontent.com/assets/9688133/26524205/b077b3ae-42f9-11e7-8943-43dce021af22.png)
![screen shot 2017-05-27 at 16 25 31](https://cloud.githubusercontent.com/assets/9688133/26524206/b07a172a-42f9-11e7-9b3b-c7993e033824.png)

**Comment by j-kohl** [comment]
fixed in last merge
