### ISSUE TITLE
Change icons in TaskActivity, AddNewTaskActivity from Vector Drawable 

### ISSUE THREAD

**Issue by KhalidAwil** [janacm/Momenta-Capstone#66]
Convert from Vector Drawable to PNGs with different densities because vector drawables are supported only for API 21 and above, while our min API level is 15

**Comment by nnam-ibe** [comment]
did you do this already?

**Comment by KhalidAwil** [comment]
Naw. Will do soon tho. Only did it for one icon

**Comment by nnam-ibe** [comment]
Aii, no rush I just wanted to know if I could close this.
Also last time I tried I tested Kitkat, it seemed to work fine on my emulator, maybe I'm mistaken.

**Comment by KhalidAwil** [comment]
Lol test with jellybean and then we'll know were okay

**Comment by nnam-ibe** [comment]
I think Miguel's requirement was 70%, with KitKat we have well over 80. Personally, I think you should up the min to 19 and close this.
